# fly.toml app configuration file generated for gpt-image-1-playground on 2025-07-30T13:45:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-image-1-playground'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"
  build-target = "runner"
  
[build.args]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Storage mode for Fly.io deployment
  NEXT_PUBLIC_IMAGE_STORAGE_MODE = "indexeddb"
  
# Build is handled in Dockerfile, no release command needed
